// <auto-generated/>
using System;
using System.Reflection;

[assembly: AssemblyTitleAttribute("GLWpfControl")]
[assembly: AssemblyProductAttribute("OpenTK.GLWpfControl")]
[assembly: AssemblyDescriptionAttribute("A native WPF control for OpenTK 4.X.")]
[assembly: AssemblyVersionAttribute("3.2.2")]
[assembly: AssemblyFileVersionAttribute("3.2.2")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2020 Team OpenTK.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GLWpfControl";
        internal const System.String AssemblyProduct = "OpenTK.GLWpfControl";
        internal const System.String AssemblyDescription = "A native WPF control for OpenTK 4.X.";
        internal const System.String AssemblyVersion = "3.2.2";
        internal const System.String AssemblyFileVersion = "3.2.2";
        internal const System.Boolean CLSCompliant = true;
        internal const System.String AssemblyCopyright = "Copyright (c) 2020 Team OpenTK.";
    }
}
