// <auto-generated/>
using System;
using System.Reflection;

[assembly: AssemblyTitleAttribute("GLWpfControl")]
[assembly: AssemblyProductAttribute("OpenTK.GLWpfControl")]
[assembly: AssemblyDescriptionAttribute("A native WPF control for OpenTK 3.X.")]
[assembly: AssemblyVersionAttribute("2.1.0")]
[assembly: AssemblyFileVersionAttribute("2.1.0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2019 Team OpenTK.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GLWpfControl";
        internal const System.String AssemblyProduct = "OpenTK.GLWpfControl";
        internal const System.String AssemblyDescription = "A native WPF control for OpenTK 3.X.";
        internal const System.String AssemblyVersion = "2.1.0";
        internal const System.String AssemblyFileVersion = "2.1.0";
        internal const System.Boolean CLSCompliant = true;
        internal const System.String AssemblyCopyright = "Copyright (c) 2019 Team OpenTK.";
    }
}
