// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System;
using System.Reflection;

[assembly: AssemblyTitle("GLWpfControl")]
[assembly: AssemblyProduct("OpenTK.GLWpfControl")]
[assembly: AssemblyDescription("A native WPF control for OpenTK 3.X.")]
[assembly: AssemblyVersion("3.3.0")]
[assembly: AssemblyFileVersion("3.3.0")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyCopyright("Copyright (c) 2020 Team OpenTK.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GLWpfControl";
        internal const System.String AssemblyProduct = "OpenTK.GLWpfControl";
        internal const System.String AssemblyDescription = "A native WPF control for OpenTK 3.X.";
        internal const System.String AssemblyVersion = "3.3.0";
        internal const System.String AssemblyFileVersion = "3.3.0";
        internal const System.Boolean CLSCompliant = true;
        internal const System.String AssemblyCopyright = "Copyright (c) 2020 Team OpenTK.";
    }
}
